### ISSUE TITLE
dev-branch debugging

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#28]
Now running into:
```sh
~/gh/inrupt/pod-server $ npm start

> pod-server@0.3.0 start /Users/michiel/gh/inrupt/pod-server
> node dist/standalone.js

NOTICE: a draft/experimental feature (sessionManagement) enabled, future updates to this feature will be released as MINOR releases
WARNING: configuration cookies.keys is missing, this option is critical to detect and ignore tampered cookies
WARNING: a quick start development-only sign key is used, you are expected to provide your own during provider#initialize
WARNING: a quick start development-only feature devInteractions is enabled, you are expected to disable these interactions and provide your own
listening on 8080

  Error: /Users/michiel/gh/inrupt/pod-server/node_modules/solid-idp/dist/src/defaultConfiguration/views/error.ejs:7
      5|     <title><%= message %></title>
      6|     <style type="text/css">
   >> 7|       <%- include('main.css', {}); %>
      8|      </style>
      9|   </head>
      10|   <body>
  
  Could not find the include file "main.css"
      at getIncludePath (/Users/michiel/gh/inrupt/pod-server/node_modules/ejs/lib/ejs.js:165:13)
      at includeFile (/Users/michiel/gh/inrupt/pod-server/node_modules/ejs/lib/ejs.js:291:19)
      at include (/Users/michiel/gh/inrupt/pod-server/node_modules/ejs/lib/ejs.js:666:16)
      at eval (eval at compile (/Users/michiel/gh/inrupt/pod-server/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:14:17)
      at returnedFn (/Users/michiel/gh/inrupt/pod-server/node_modules/ejs/lib/ejs.js:668:17)
      at /Users/michiel/gh/inrupt/pod-server/node_modules/consolidate/lib/consolidate.js:645:16
      at /Users/michiel/gh/inrupt/pod-server/node_modules/consolidate/lib/consolidate.js:161:5
      at Promise._execute (/Users/michiel/gh/inrupt/pod-server/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (/Users/michiel/gh/inrupt/pod-server/node_modules/bluebird/js/release/promise.js:488:18)
      at new Promise (/Users/michiel/gh/inrupt/pod-server/node_modules/bluebird/js/release/promise.js:79:10)
      at promisify (/Users/michiel/gh/inrupt/pod-server/node_modules/consolidate/lib/consolidate.js:154:10)
      at Function.exports.ejs.render (/Users/michiel/gh/inrupt/pod-server/node_modules/consolidate/lib/consolidate.js:641:10)
      at /Users/michiel/gh/inrupt/pod-server/node_modules/consolidate/lib/consolidate.js:181:27
      at /Users/michiel/gh/inrupt/pod-server/node_modules/consolidate/lib/consolidate.js:101:5
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

**Comment by michielbdejong** [comment]
That's https://github.com/inrupt/solid-idp/blob/master/src/defaultConfiguration/views/main.css which should be right next to https://github.com/inrupt/solid-idp/blob/master/src/defaultConfiguration/views/error.ejs. Will try to remove the reference and see if i can get error.ejs to render

**Comment by michielbdejong** [comment]
fixed in https://github.com/inrupt/solid-idp/commit/9dcb9a7be60bb99a2906e38b7dd6ed4241a6d2d1.
